// GENERATED by scripts/diagram-validators.mjs — do not edit.
// Regenerate with: pnpm run diagram:validators
/** Ajv's ValidateFunction, as far as the resolver uses it (ajv is not our dependency). */
export interface ValidateFunction {
  (data: unknown): boolean;
  errors?: null | ErrorObject[];
}
export interface ErrorObject {
  keyword: string;
  instancePath: string;
  schemaPath: string;
  params: Record<string, unknown>;
  message?: string;
}

/** Tag (or "tag-schema") → the fingerprint of the schema it was compiled from. */
export const TAGS: Readonly<Record<string, string>>;
/** Schema fingerprint → validator, for every schema the resolver compiles. */
export const VALIDATORS: Readonly<Record<string, ValidateFunction>>;
/** The fingerprint of a schema object, as the shim computes it at runtime. */
export function fingerprint(schema: unknown): string;
