// The curated notebook icon set. Keys are lucide slugs and are what the
// backend stores (and auto-picks — see `auto_notebook_icon` in
// src-tauri/src/commands.rs; new auto-pick names must be added here too).
import {
  Baby,
  Book,
  BookOpen,
  Briefcase,
  Bug,
  Calendar,
  Clock,
  Car,
  Cat,
  Code,
  Command,
  DollarSign,
  Dog,
  Drama,
  Dumbbell,
  Film,
  Flame,
  FlaskConical,
  Gamepad2,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Landmark,
  Map,
  Monitor,
  Music,
  Newspaper,
  Palette,
  Plane,
  Rocket,
  Sailboat,
  Scale,
  Shirt,
  ShoppingCart,
  Trees,
  Users,
  Utensils,
  WandSparkles,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const NOTEBOOK_ICONS: Record<string, LucideIcon> = {
  "book-open": BookOpen,
  briefcase: Briefcase,
  plane: Plane,
  "dollar-sign": DollarSign,
  home: Home,
  heart: Heart,
  dumbbell: Dumbbell,
  utensils: Utensils,
  music: Music,
  film: Film,
  "gamepad-2": Gamepad2,
  "graduation-cap": GraduationCap,
  "flask-conical": FlaskConical,
  code: Code,
  car: Car,
  trees: Trees,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  wrench: Wrench,
  scale: Scale,
  landmark: Landmark,
  globe: Globe,
  palette: Palette,
  newspaper: Newspaper,
  rocket: Rocket,
  calendar: Calendar,
  book: Book,
  map: Map,
  "shopping-cart": ShoppingCart,
  users: Users,
  sailboat: Sailboat,
  bug: Bug,
  drama: Drama,
  shirt: Shirt,
  command: Command,
  monitor: Monitor,
  flame: Flame,
  "wand-sparkles": WandSparkles,
  clock: Clock,
};

/** The component for a stored icon name — unknown/empty falls back to the
 *  default book, so stale names never break rendering. */
export function notebookIcon(name: string | undefined): LucideIcon {
  return (name && NOTEBOOK_ICONS[name]) || BookOpen;
}

// Keep this list in sync with Rust in `src-tauri/src/db.rs` (`NOTEBOOK_PALETTE`)
// — that copy seeds new-notebook colors. The validator only checks hex form.
export const NOTEBOOK_PALETTE = [
  "#eb5757",
  "#e8a33d",
  "#d9b13b",
  "#4cb782",
  "#4fc1c9",
  "#5e9bd2",
  "#9b87f5",
  "#e274b6",
  "#c1765a",
  "#98a562",
  "#8a93a6",
];
