import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = createRequire(require.resolve('@eraserlabs/diagrams/package.json'))('playwright-core');
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
const page = await browser.newPage({ viewport: { width: 1200, height: 800 } });
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
try {
  await page.goto(process.argv[2] ?? 'http://127.0.0.1:8795/scripts/resource-budget/index.html');
  await page.getByText('Original body b', { exact: true }).waitFor();
  await page.evaluate(() => { resourceBudget.slow('a'); resourceBudget.open('a'); });
  await page.getByText('Loading note…', { exact: true }).waitFor();
  await page.evaluate(() => resourceBudget.open('b'));
  await page.getByText('Original body b', { exact: true }).waitFor();
  await page.evaluate(() => resourceBudget.release());
  await page.waitForTimeout(100);
  assert.equal(await page.getByText('Original body a', { exact: true }).count(), 0, 'late note load cannot replace current note');
  await page.getByRole('button', { name: 'Edit note', exact: true }).click();
  const editor = page.locator('[contenteditable=true]');
  await editor.fill('Edited report body');
  await page.evaluate(() => resourceBudget.refresh());
  await page.waitForTimeout(100);
  assert.equal(await editor.innerText(), 'Edited report body', 'refresh preserves unsaved editor text');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.getByText('Edited report body', { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => resourceBudget.notes.get('b').content.trim()), 'Edited report body');
  await page.evaluate(() => resourceBudget.export('table'));
  assert.equal(await page.evaluate(() => resourceBudget.exported), 'xlsx', 'summary table export resolves from full body');
  await page.evaluate(() => resourceBudget.export('b'));
  assert.equal(await page.evaluate(() => resourceBudget.exported), 'docx');
  await page.evaluate(() => resourceBudget.create());
  assert.equal(await page.evaluate(() => resourceBudget.state().notes.some((n) => 'content' in n || 'prompt' in n)), false, 'generation/create results cannot leak bodies into collection');
  await page.evaluate(() => { resourceBudget.fail('a'); });
  await page.evaluate(() => resourceBudget.delete(['a', 'b']));
  assert.equal(await page.evaluate(() => resourceBudget.deleted), 0, 'failed snapshot prevents deletion');
  await page.evaluate(() => resourceBudget.fail(''));
  await page.evaluate(() => resourceBudget.delete(['a', 'b']));
  assert.equal(await page.evaluate(() => resourceBudget.notes.has('b')), false);
  await page.evaluate(() => resourceBudget.undo());
  assert.deepEqual(await page.evaluate(() => resourceBudget.restores.map((n) => [n.content.trim(), n.prompt])), [
    ['Original body a', 'Preserve instructions a'], ['Edited report body', 'Preserve instructions b'],
  ]);
  await page.evaluate(() => resourceBudget.redo());
  assert.equal(await page.evaluate(() => resourceBudget.notes.has('restored-0') || resourceBudget.notes.has('restored-1')), false, 'redo deletes the new restored ids');
  await page.evaluate(() => resourceBudget.undo());
  assert.equal(await page.evaluate(() => resourceBudget.notes.has('restored-2') && resourceBudget.notes.has('restored-3')), true);
  await page.evaluate(() => resourceBudget.shaders());
  await page.waitForTimeout(500);
  const before = await page.evaluate(() => resourceBudget.draws);
  await page.waitForTimeout(1000);
  const visibleDraws = await page.evaluate((before) => resourceBudget.draws - before, before);
  assert(visibleDraws > 10, 'visible shaders animate');
  await page.screenshot({ path: '/tmp/alchemy-resource-shaders.png' });
  await page.evaluate(() => window.scrollTo(0, 900));
  await page.waitForTimeout(100);
  const hiddenStart = await page.evaluate(() => resourceBudget.draws);
  await page.waitForTimeout(1000);
  const hiddenDraws = await page.evaluate((start) => resourceBudget.draws - start, hiddenStart);
  assert.equal(hiddenDraws, 0, 'offscreen shaders stop drawing');
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.waitForTimeout(200);
  assert(await page.evaluate((start) => resourceBudget.draws > start, hiddenStart));
  await page.evaluate(() => resourceBudget.close());
  await page.waitForTimeout(100);
  const closedStart = await page.evaluate(() => resourceBudget.draws);
  await page.waitForTimeout(100);
  assert.equal(await page.evaluate(() => resourceBudget.draws), closedStart);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ result: 'passed', visibleDrawsPerSecond: visibleDraws, offscreenDrawsPerSecond: hiddenDraws, scenarios: ['late response', 'editing and save', 'table and prose export', 'body retention', 'failed delete read', 'delete undo redo twice', 'visible/offscreen/unmounted shaders'] }, null, 2));
} catch (error) {
  console.error('Browser errors:', errors);
  console.error((await page.locator('body').innerText()).slice(0, 3000));
  throw error;
} finally { await browser.close(); }
