"""Alchemy MCP integration for Prime Agent (installed by Alchemy's
Settings → Agents connect; the layout follows prime-agent's
docs/mcp-integrations.md reference implementation)."""

import json
import os
import sys
from pathlib import Path

from rlm import McpIntegration


def _discovery_path() -> Path:
    if sys.platform == "darwin":
        return Path.home() / "Library/Application Support/com.thrashr888.alchemy/mcp.json"
    if sys.platform == "win32":
        return Path(os.environ["APPDATA"]) / "com.thrashr888.alchemy/mcp.json"
    data_home = Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local/share"))
    return data_home / "com.thrashr888.alchemy/mcp.json"


class Alchemy(McpIntegration):
    # Matches the mcpServers key Alchemy writes to ~/.prime/agent/settings.json;
    # the host-resolved URL from that entry wins over this fallback, so a
    # non-default MCP port keeps working.
    server = "alchemy"
    url = "http://127.0.0.1:41414/mcp"

    async def _resolve_token(self) -> str:
        # The discovery file is generated by the running app with owner-only
        # permissions. Read it at connection time so a token rotation or app
        # upgrade does not bake stale credentials into the installed skill.
        try:
            token = json.loads(_discovery_path().read_text())["token"]
        except (OSError, KeyError, TypeError, json.JSONDecodeError) as error:
            raise RuntimeError(
                "Alchemy authentication is unavailable; restart Alchemy and reconnect Prime"
            ) from error
        if not isinstance(token, str) or not token:
            raise RuntimeError("Alchemy discovery file has no authentication token")
        return token


alchemy = Alchemy()

# Forward bare module access (`import alchemy; await alchemy.<tool>(...)`) to
# the instance, but NOT the names the kernel bootstrap probes — forwarding
# `run` would make it treat the module as a callable skill and break tool
# dispatch.
_RESERVED = {"run", "__wrapped__", "__call__"}


def __getattr__(name):
    if name.startswith("_") or name in _RESERVED:
        raise AttributeError(name)
    return getattr(alchemy, name)
